apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: tofork
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: tofork/user-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: SERVER_PORT
          value: "8081"
        - name: APP_FRONTEND_URL
          value: "http://localhost"
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI
          value: "http://localhost/login/oauth2/code/google"
        - name: SERVER_FORWARD_HEADERS_STRATEGY
          value: "framework"
        - name: SPRING_SQL_INIT_MODE
          value: "always"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/tofork"
        - name: JWT_SECRET
          value: "mySecretKeyWhichIsLongEnoughForHS256"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: GOOGLE_CLIENT_ID
          valueFrom:
              secretKeyRef:
                name: google-secret
                key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
              secretKeyRef:
                name: google-secret
                key: GOOGLE_CLIENT_SECRET
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_USER
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_EXCHANGE
          value: "tofork.exchange"
        - name: RABBITMQ_BOOKING_QUEUE
          value: "booking.queue"
        - name: RABBITMQ_ORDER_QUEUE
          value: "order.queue"
        - name: RABBITMQ_PAYMENT_QUEUE
          value: "payment.queue"
        - name: USER_SERVICE_URL
          value: "http://user-service:8081"
        - name: ORDER_SERVICE_URL
          value: "http://order-service:8082"
        - name: BOOKING_SERVICE_URL
          value: "http://booking-service:8085"
        - name: PAYMENT_SERVICE_URL
          value: "http://payment-service:8084"
        - name: RESTAURANT_SERVICE_URL
          value: "http://restaurant-service:8083"
