apiVersion: v1
kind: Service
metadata:
  name: restaurant-service # Nome DNS interno
  namespace: tofork
spec:
  selector:
    app: restaurant-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP